### ISSUE TITLE
npm install failed: postinstall error

### ISSUE THREAD

**Issue by robinstickel** [me-and-company/web-project-kit#1]
I followed the installation instructions but npm install failed with the following error: 

> startertkit@1.0.0 postinstall /Users/robinstickel/Dev/test
> node ./postinstall.js
>
>module.js:538
>    throw err;
>    ^
>
>Error: Cannot find module '/Users/robinstickel/Dev/test/postinstall.js'
>    at Function.Module._resolveFilename (module.js:536:15)
>    at Function.Module._load
>
>  (module.js:466:25)
>     at Function.Module.runMain (module.js:676:10)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! startertkit@1.0.0 postinstall: `node ./postinstall.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the startertkit@1.0.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/robinstickel/.npm/_logs/2017-12-22T11_31_06_985Z-debug.log

**Comment by man-oi** [comment]
oh yeah, the command had changed [(commit)](https://github.com/me-and-company/web-project-kit/commit/d321894de6ea8c9607b1ef4503665467dc6a6282) without committing the file.
should work again :)
