### ISSUE TITLE
Reduce the CSS file size

### ISSUE THREAD

**Issue by man-oi** [me-and-company/web-project-kit#10]
The initial CSS file size is very big (~400kb), thats not working for a goog performance budget. see http://www.performancebudget.io/

the basic file size should be under 80kb

maybe options can be helpful, like the inuit framework do it. https://github.com/csswizardry/inuit.css/blob/master/_defaults.scss

**Comment by man-oi** [comment]
is now implemented in the branch https://github.com/me-and-company/web-project-kit/tree/feature/sass-optimizing, with further changes.
The most important changes are:
- 02_tools/_functions is now 00_functions/_base
- removed container class from float-grid
- removed baseline/base-spacing helpers
- added use options

with the two use-options to false, css output is now 13,5kb (it never was ~400kb.. it was ~60kb)

@robinstickel @chrSchroers Would you like to take a look at the Branch?

**Comment by robinstickel** [comment]
Looks good for me 👍

**Comment by robinstickel** [comment]
On another note: Do we really need all the grid variations? I can't remember using the float or flex grid. Looks like we are using the inlineblock grid most of the time anyway. Correct me if I'm wrong, but maybe we can throw these out?

**Comment by man-oi** [comment]
the grid variant used is defined by $grid-variation. I have now added $use-grid to completely do without the grid system. I think that covers all the possibilities.

**Comment by man-oi** [comment]
is merged https://github.com/me-and-company/web-project-kit/commit/9441addc2fcef8f76dd61ab6402cad92c8c10e58
