### ISSUE TITLE
javascript modules / classes / factories

### ISSUE THREAD

**Issue by man-oi** [me-and-company/web-project-kit#14]
Define a default template for Javascript modules.

**Comment by chrSchroers** [comment]
This was done with commit [70dde76](https://github.com/me-and-company/grace/commit/70dde764cbfde7d1cba04c652cd85b36a392e6f9). Merged the documentation into master now with commit [28b7244](https://github.com/me-and-company/grace/commit/28b724495555b6bb8e79068da659597f588c1a1a)
