### ISSUE TITLE
Variables for $primary-font-family und $secondary-font-family

### ISSUE THREAD

**Issue by robinstickel** [me-and-company/web-project-kit#3]
Include more than $base-font-family

**Comment by man-oi** [comment]
Dein Vorschlag wäre also aus $base-font-family die beiden zu machen, oder zusätzlich?
Spricht erstmal nichts dagegen, oft braucht man ja auch zwei

**Comment by robinstickel** [comment]
Ich glaube primary und secondary reicht, oder? Wir haben sehr selten mehr als zwei verschiedene Fonts im Einsatz, oder?

**Comment by man-oi** [comment]
Ja würde ich auch sagen, können wir gerne einführen. Überlege ob wir $base-font-family noch als Alias benutzen wollen. Also dann:
$base-font-family: $primary-font-family;

**Comment by robinstickel** [comment]
Hatte ich auch überlegt, kann dann aber ggf. zu Verwirrung führen, oder? Entscheide aber gerne selbst 😄

**Comment by man-oi** [comment]
Vor allem was ist eigentlich _$primary_? Ist das die meist benutzte Schrift, oder die Schrift für Überschriften? Wenn $primary für Überschriften und $secondary für normalen Text wäre, dann wäre $base auch eher gleich $secondary 😄

Vielleicht sollten wir über die Benennung nochmal nachdenken? Denke gerade eher an sowas wie:
$head-font-family
$base-font-family

**Comment by robinstickel** [comment]
Ich würde es nicht in Headlines und normalen Text trennen. Manchmal sind sowohl Headlines als auch normaler Text in der gleichen Schriftart und nur Zitate z.B. in einer anderen. Ich sehe $primary als HAUPT Schriftart. Jene die eben am meisten genutzt wird. Und $secondary dann eben für eine "Nebenschrift". Das kann sowohl die Headline, aber auch ein Zitatmodul sein.

Vielleicht macht es dann schon Sinn sowohl $base, als auch $primary-font-family und $secondary-font-family zu machen und so zu definieren:
$base-font-family: $primary oder $secondary;

**Comment by man-oi** [comment]
find ich gut $primary als main schrift zu sehen. hab das jetzt mal im branch feature/secondary-font-family umgesetzt, mit einem kleinen Kommentar für weitere font-families

**Comment by man-oi** [comment]
merged

https://github.com/me-and-company/web-project-kit/commit/4fd705f4870c10e410714d8e2a417cfba20e5ac2
